LineageSettings: fix api lint
Fix a typo and hide a validator, which was not hidden
by mistake.

```
lineage-sdk/sdk/src/java/lineageos/providers/LineageSettings.java:2776: warning: Field LineageSettings.Secure.GESTURE_BACK_EXCLUDE_TOP_VALIDATOR references hidden type lineageos.providers.LineageSettings.Validator. (ErrorWhenNew) [HiddenT
ypeParameter]
lineage-sdk/sdk/src/java/lineageos/providers/LineageSettings.java:2776: error: Class lineageos.providers.LineageSettings.Validator is hidden but was referenced (in field type) from public field lineageos.providers.LineageSettings.Secure.G
ESTURE_BACK_EXCLUDE_TOP_VALIDATOR [ReferencesHidden]
lineage-sdk/sdk/src/java/lineageos/providers/LineageSettings.java:2942: warning: Field LineageSettings.Secure.VOLUME_PANEL_ON_LEFT_VALIDATOR references hidden type lineageos.providers.LineageSettings.Validator. (ErrorWhenNew) [HiddenTypeP
arameter]
lineage-sdk/sdk/src/java/lineageos/providers/LineageSettings.java:2942: error: Class lineageos.providers.LineageSettings.Validator is hidden but was referenced (in field type) from public field lineageos.providers.LineageSettings.Secure.V
OLUME_PANEL_ON_LEFT_VALIDATOR [ReferencesHidden]
```

Change-Id: I71db41bc6f797d77fb281c989d9dcd7299036a25
Signed-off-by: Alexander Martinz <amartinz@shiftphones.com>